### ISSUE TITLE
이미지 업로드 확장자가 다 허용임?

### ISSUE THREAD

**Issue by baekteun** [GSM-MSG/GCMS-FrontEnd-V2#159]
### Describe

걸러지는 확장자가 없는데?

<img width="1147" alt="스크린샷 2023-02-27 오전 1 32 25" src="https://user-images.githubusercontent.com/74440939/221423471-94b9dedd-3826-4165-baac-38e124a26f7e.png">

**Comment by chanwoo00106** [comment]
당연히 image만 선택할 수 있게 걸러야지
