### ISSUE TITLE
동아리 리스트 view 타입 바꾸는데 로그아웃 당함

### ISSUE THREAD

**Issue by baekteun** [GSM-MSG/GCMS-FrontEnd-V2#163]
### Describe

전공이나 자율이나 사설로 동아리 리스트 view 타입 바꾸니 로그아웃이 당해요.. 화면 리프레시하면 다시 로그인되고요..

https://user-images.githubusercontent.com/74440939/221423954-a30a794c-ff26-4429-bc7c-4c5b4c098f36.mov

**Comment by chanwoo00106** [comment]
이건 고쳤으니 안심하시게

**Comment by baekteun** [comment]
> 이건 고쳤으니 안심하시게

5
