### ISSUE TITLE
이 친구 약간 sticky로 있는게 좋을거같지 않음?

### ISSUE THREAD

**Issue by baekteun** [GSM-MSG/GCMS-FrontEnd-V2#164]
### Describe

같이 그냥 올라가버리는데 고정시키는게 더 자연스러울거같은뎁
<img width="234" alt="스크린샷 2023-02-27 오전 1 50 37" src="https://user-images.githubusercontent.com/74440939/221424414-efa94f4e-12ed-4274-a956-dddcb4f32e76.png">

**Comment by chanwoo00106** [comment]
인정합니다
