### ISSUE TITLE
동아리신청 활성화/비활성화 단어 개선

### ISSUE THREAD

**Issue by baekteun** [GSM-MSG/GCMS-FrontEnd-V2#166]
### Describe

동아리 열기 닫기 뭔가 미묘한데, 신청 받기 / 신청 안받기, 신청 활성화 / 비활성화, 모집 활성화 / 비활성화
음.. 더 좋은 단어 없을까요

<img width="191" alt="스크린샷 2023-02-27 오전 2 02 16" src="https://user-images.githubusercontent.com/74440939/221424997-0766fc9a-987a-4ba3-88d9-c9db5cbef2c1.png">

<img width="253" alt="스크린샷 2023-02-27 오전 2 03 51" src="https://user-images.githubusercontent.com/74440939/221425063-11e766c9-4096-4fe9-abc5-3a88a66071ee.png">

**Comment by chanwoo00106** [comment]
니가 생각해와

**Comment by jjaejjae12** [comment]
開 閉 (열개, 닫을 폐) ㄱ

**Comment by chanwoo00106** [comment]
동아리를 열고 닫는 버튼이 모두 switch로 바뀌었기 때문에 이 issue는 닫습니다
