### ISSUE TITLE
설정버튼인지 모르겠음

### ISSUE THREAD

**Issue by baekteun** [GSM-MSG/GCMS-FrontEnd-V2#167]
### Describe

걍 디자인용으로 배치한 뱃지같은 느낌이 듬.. 이건 디자인한테 문의해야하나?

<img width="182" alt="스크린샷 2023-02-27 오전 2 04 54" src="https://user-images.githubusercontent.com/74440939/221425120-3b2673aa-402c-4988-af0c-179fa3682f73.png">

**Comment by chanwoo00106** [comment]
디자이너 한테 따져
