### ISSUE TITLE
레이아웃

### ISSUE THREAD

**Issue by googoo81** [GSM-MSG/GCMS-FrontEnd-V2#233]
![캡처](https://user-images.githubusercontent.com/101445027/225775575-778dad3f-a784-4cb6-9235-8c542b900201.PNG)
![q](https://user-images.githubusercontent.com/101445027/225775579-dff5334f-6049-4d49-b946-af61a669535b.PNG)
![daf](https://user-images.githubusercontent.com/101445027/225775582-57eda375-bd9d-4882-94e4-45805159e0cb.PNG)
레이아웃이 위치가 달라요 전공이랑 사설 페이지는 위치가 같은데 자율 페이지는 조금 더 오른쪽으로 치우쳐 있습니다

**Comment by chanwoo00106** [comment]
이거 window에서만 생기는 문제야
오른쪽에 scrollbar 때문에 페이지가 왼쪽으로 밀리는 거야
전에 성훈이가 같은 이슈를 날려서 이건 그냥 닫을게
