### ISSUE TITLE
동아리 제목이 너무 길면 라인 브레이크 해주세요

### ISSUE THREAD

**Issue by kimsh153** [GSM-MSG/GCMS-FrontEnd-V2#246]
### Describe

<img width="738" alt="스크린샷 2023-03-20 오전 12 15 21" src="https://user-images.githubusercontent.com/81547954/226185758-7d786c45-237a-4db2-ba5b-e84523ec0698.png">
너무 화면이 길게 내려가요

**Comment by chanwoo00106** [comment]
제목을 라인 브레이크 하는 건 좀 아닌 것 같으니까 제목에 길이 제한을 주는 게 좋을 것 같아요
