### ISSUE TITLE
폴드폰 반응형이 이상해요

### ISSUE THREAD

**Issue by jjaejjae12** [GSM-MSG/GCMS-FrontEnd-V2#247]
### Describe

사이드바 컴포넌트때문에 스타일이 이상해진다
<img width="371" alt="image" src="https://user-images.githubusercontent.com/81688137/226186150-585b32bc-3395-4457-8f37-ef4022429dc9.png">

**Comment by chanwoo00106** [comment]
사이드바가 아니라 header에 있는 padding 때문에 밀려난 거에요
하지만 이걸 하면 반응형을 각 잡고 해야할 것 같아요
폴드폰 같이 엄청 얇은 폰이 많지 않아서 하고 싶으면 하는 걸로

**Comment by jjaejjae12** [comment]
안드,ios로 gcms가 이미 있으니깐 걍 안해도될듯
