### ISSUE TITLE
통계페이지 반응형이 안되요

### ISSUE THREAD

**Issue by jjaejjae12** [GSM-MSG/GCMS-FrontEnd-V2#248]
### Describe

<img width="344" alt="image" src="https://user-images.githubusercontent.com/81688137/226186334-85274060-5f97-4a03-9793-b1a4a47cbad0.png">

**Comment by chanwoo00106** [comment]
저는 반응형을 SE까지만 하기 때문에 폴드는 지원을 안 했을 수 있어요
근데 폴드 사이즈는 굉장히 작은데다 크기도 폴드 1 크기여서 이제는 거의 사용하지 않는 크기라고 생각해요

**Comment by jjaejjae12** [comment]
여기도 딱히 필요없을것 같아서 그냥 닫을게
