### ISSUE TITLE
관리자계정으로 통계에서 동아리별 출력을 할때 다운이 안 되거나 손상이 되어있는 엑셀파일이 나옵니다

### ISSUE THREAD

**Issue by kimsh153** [GSM-MSG/GCMS-FrontEnd-V2#254]
### Describe

관리자계정으로 통계에서 동아리별 출력을 할때 다운이 안 되거나 손상이 되어있는 엑셀파일이 나옵니다

**Comment by chanwoo00106** [comment]
다운이 안되는 건 속도가 느려서 그런 것 같고 손상이 되었다는 건 어떻게 손상이 되었는지 불명확합니다
조금 더 자세하게 작성해 주세요

**Comment by kimsh153** [comment]
아 저거 손상오류는 동아리 설명 2만자 때문이였네요
그리고 다운이 안 되는 자율동아리 동아리별 엑셀 에러는 동아리 500이 뜨네요
