### ISSUE TITLE
동아리 멤버 페이지는 title이 적용되지 않았어요

### ISSUE THREAD

**Issue by kangkong0805** [GSM-MSG/GCMS-FrontEnd-V2#256]
### Describe

![image](https://user-images.githubusercontent.com/87346613/226220567-c82dabb0-64f2-4512-9fe4-5a897a66218e.png)

**Comment by chanwoo00106** [comment]
애초에 멤버 페이지는 동아리원들만 볼 수 있어야 하는 거 아닌가요?

**Comment by chanwoo00106** [comment]
아 title을 말하는 거였어??

**Comment by kangkong0805** [comment]
어... 사실 title의 목적이 크긴 한데 그것도 seo 적용되니까 좀 애매하네

**Comment by chanwoo00106** [comment]
신청자 목록이랑 동아리 수정 페이지는 다 되는데 멤버 페이지만 안되면 이상하니까 일단 넣기는 해야함
